# Generated by Django 3.2.14 on 2022-07-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='phone_number',
        ),
    ]
